DROP DATABASE IF EXISTS nominas;
CREATE DATABASE nominas
CHARACTER SET utf8
COLLATE utf8_spanish_ci;

USE nominas;

CREATE TABLE trabajador(
	CodTra INT(11) AUTO_INCREMENT PRIMARY KEY,
	NomTra VARCHAR(40) NOT NULL,
	NifTra VARCHAR(9) NOT NULL UNIQUE,
	NafSSTra VARCHAR(12) NOT NULL UNIQUE
);

CREATE TABLE empresa(
	CodEmp INT(11) AUTO_INCREMENT PRIMARY KEY,
	NomEmp VARCHAR(50) NOT NULL,
	CifEmp VARCHAR(9) NOT NULL UNIQUE,
	DirEmp VARCHAR(100),
	CCCEmp VARCHAR(11) NOT NULL UNIQUE
);

CREATE TABLE traemp(
	CodTra INT(11),
	CodEmp INT(11),
	Convenio VARCHAR(100),
	GrupoCot VARCHAR(50) NOT NULL,
	CatProf VARCHAR(100) NOT NULL,
	FecInTra DATE NOT NULL,
	FecSalTra DATE,
	PRIMARY KEY(CodTra,CodEmp),
	CONSTRAINT fk_tra_traemp FOREIGN KEY(CodTra)
	REFERENCES trabajador(CodTra) ON UPDATE CASCADE,
	CONSTRAINT fk_emp_traemp FOREIGN KEY(CodEmp)
	REFERENCES empresa(CodEmp) ON UPDATE CASCADE
);	
